SELECT JOB_CODE FROM employees.employees WHERE JOB_CODE = 502;
UPDATE EMPLOYEE
SET JOB_CODE = '501'
WHERE EMP_NUM = '107';
DELETE FROM employees
WHERE EMP_LNAME = 'Smithfield' AND EMP_FNAME = 'William' AND EMP_HIREDATE = '22-Jun-17' AND JOB_CODE = '500'
LIMIT 1 ;
DELETE FROM employees 
WHERE EMP = '101' AND '102' AND '103' AND '104' AND '105' AND '106'AND '107';
DROP TABLE employees;